// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzsCTtEzus9QavnGvX3y68bXZb2y7A4Hk',
    appId: '1:558883745304:web:f2005196339eadb124dd6d',
    messagingSenderId: '558883745304',
    projectId: 'shopx-870e3',
    authDomain: 'shopx-870e3.firebaseapp.com',
    storageBucket: 'shopx-870e3.firebasestorage.app',
    measurementId: 'G-1DRV2L7C3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMflQeLeoIte5eh9voXji-hkEhJ_ykzlI',
    appId: '1:558883745304:android:c2925c64f421398a24dd6d',
    messagingSenderId: '558883745304',
    projectId: 'shopx-870e3',
    storageBucket: 'shopx-870e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrwtx539QwTe9Xn86q0VeA0Cp7nUJ1xPw',
    appId: '1:558883745304:ios:5d5935f08949c09624dd6d',
    messagingSenderId: '558883745304',
    projectId: 'shopx-870e3',
    storageBucket: 'shopx-870e3.firebasestorage.app',
    iosBundleId: 'com.example.shopx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrwtx539QwTe9Xn86q0VeA0Cp7nUJ1xPw',
    appId: '1:558883745304:ios:5d5935f08949c09624dd6d',
    messagingSenderId: '558883745304',
    projectId: 'shopx-870e3',
    storageBucket: 'shopx-870e3.firebasestorage.app',
    iosBundleId: 'com.example.shopx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzsCTtEzus9QavnGvX3y68bXZb2y7A4Hk',
    appId: '1:558883745304:web:6d5cee49a58a59bf24dd6d',
    messagingSenderId: '558883745304',
    projectId: 'shopx-870e3',
    authDomain: 'shopx-870e3.firebaseapp.com',
    storageBucket: 'shopx-870e3.firebasestorage.app',
    measurementId: 'G-63PR65N2C2',
  );
}
